#!/bin/bash

# Set to a destination folder to copy files to
DEST="${HOME}/transfers/ao"

make clean
make
[ $? -eq 0 ] && {
  [ -x ../trim_lslo ] && {
    echo "Trimming comments from optimized LSL scripts"
    ../trim_lslo
  }
}

[ "$1" == "-c" ] && {
  mkdir -p ${DEST}
  cp iAO-core_MGJEmod_1.1.16.lslo ${DEST}/"iAO-core MGJEmod 1.1.16"
  cp iAO-HUD_Position_handler_0.0.4.lslo ${DEST}/"iAO-HUD Position handler 0.0.4"
  cp iAO-interface_MGJEmod_1.0.14.lslo ${DEST}/"iAO-interface MGJEmod 1.0.14"
  cp iAO-loadcards_0.0.9.lslo ${DEST}/"iAO-loadcards 0.0.9"
  cp iAO-ONOFF_button_color_0.0.1.lslo ${DEST}/"iAO-ONOFF button color 0.0.1"
}
